"""empty message

Revision ID: 00002
Revises: 00001
Create Date: 2025-06-15 11:40:54.596605

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00002"
down_revision: Union[str, None] = "00001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "countries", sa.Column("dial_code", sa.String(length=3), nullable=True)
    )
    op.drop_constraint(op.f("countries_deal_code_key"), "countries", type_="unique")
    op.create_unique_constraint(None, "countries", ["dial_code"])
    op.drop_column("countries", "deal_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "countries",
        sa.Column(
            "deal_code", sa.VARCHAR(length=3), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "countries", type_="unique")
    op.create_unique_constraint(
        op.f("countries_deal_code_key"),
        "countries",
        ["deal_code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("countries", "dial_code")
    # ### end Alembic commands ###
