"""empty message

Revision ID: 00008
Revises: 00007
Create Date: 2025-06-17 09:22:11.205646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00008'
down_revision: Union[str, None] = '00007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_profiles', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_profiles', 'industry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_profiles', 'industry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company_profiles', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
