"""empty message

Revision ID: 00009
Revises: 00008
Create Date: 2025-06-17 12:12:14.921552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00009'
down_revision: Union[str, None] = '00008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_account_company', 'company_profiles', ['account_id', 'company_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_company', 'company_profiles', type_='unique')
    # ### end Alembic commands ###
