"""empty message

Revision ID: 00005
Revises: 00004
Create Date: 2025-06-15 11:47:38.206596

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00005"
down_revision: Union[str, None] = "00004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "countries",
        "dial_code",
        existing_type=sa.VARCHAR(length=4),
        type_=sa.String(length=5),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "countries",
        "dial_code",
        existing_type=sa.String(length=5),
        type_=sa.VARCHAR(length=4),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
