"""empty message

Revision ID: 00007
Revises: 00006
Create Date: 2025-06-17 08:30:28.538062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00007'
down_revision: Union[str, None] = '00006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('company_profiles', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_profiles', 'industries', ['industry_id'], ['id'])
    op.drop_column('company_profiles', 'industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_profiles', type_='foreignkey')
    op.drop_column('company_profiles', 'industry_id')
    op.drop_table('industries')
    # ### end Alembic commands ###
