"""empty message

Revision ID: 00012
Revises: 00011
Create Date: 2025-06-18 13:17:09.978645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00012'
down_revision: Union[str, None] = '00011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('minted_nfts', 'recipient_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('minted_nfts', 'recipient_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
