"""empty message

Revision ID: 00011
Revises: 00010
Create Date: 2025-06-18 11:01:46.908049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00011'
down_revision: Union[str, None] = '00010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minted_nfts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('minted_nfts', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('minted_nfts', 'metadata_json')
    op.drop_column('minted_nfts', 'name')
    # ### end Alembic commands ###
